#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link https://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license https://www.yiiframework.com/license/
 */

// Режим задаётся окружением (docker-compose.yml), а не правкой этого файла: иначе
// единственной защитой от трассировок и Gii на боевом сервере остаётся «не забыть
// закомментировать две строки».
defined('YII_DEBUG') or define('YII_DEBUG', (getenv('YII_DEBUG') ?: '1') === '1');
defined('YII_ENV') or define('YII_ENV', getenv('YII_ENV') ?: 'dev');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
